project-fika/Fika-Plugin

README.md
Changes the link from a discord channel to an invite to the discord server.
=> Discord invite

Fika.Core/Coop/GameMode/CoopGame.cs
No functionality changed. Tested without issues.
=> decouple despawnbot from spawning bots.

Fika.Core/Coop/GameMode/CoopGame.cs, Fika.Core/Networking/FikaClient.cs
=> Change wording to be "raid server" rather than just "server"

Fika.Core/FikaPlugin.cs
Latest modules has fixed the rebrand issue for singleplayer module
=> Fix Dep from spt to SPT

Fika.Core/Coop/GameMode/CoopGame.cs
Untested. This should make the save request async preventing the game from locking up.
=> Make SavePlayer async

Fika.Core/Console/FikaCommands.cs, Fika.Core/Coop/Components/CoopHandler.cs, Fika.Core/Coop/GameMode/CoopGame.cs, Fika.Core/Networking/FikaServer.cs
This pull request contains the following changes:
* Added logging for both in the in-game console as well as in the bepinex log whenever a user hits their extract key, this will allow support to get a better idea of whether the user has overlays on that prevent the key from working, or if the issue is elsewhere.
* Adds a debug command in debug builds to forcefully despawn AI
* Adds better checking for local IP addresses, before we were only checking 192.168.* now we're checking all local IP's defined in RFC1918
=> Various small changes

Fika.Core/Coop/Components/CoopHalloweenEventManager.cs, Fika.Core/Coop/GameMode/CoopGame.cs, Fika.Core/Networking/FikaClient.cs, Fika.Core/Networking/Packets/GameWorld/HalloweenEventPacket.cs
This PR fixes #85 
Might be a better way to do the syncing between clients, for now this seems to work as intended between both the host and clients.. Event now runs as normal (Observed in SPT)
=> Fix ravangeZryachiyEvent halloween event

Fika.Core/Coop/ClientClasses/CoopClientSharedQuestController.cs, Fika.Core/Coop/Players/CoopBot.cs, Fika.Core/Coop/Players/CoopPlayer.cs, Fika.Core/Coop/Players/ObservedCoopPlayer.cs, Fika.Core/Networking/FikaClient.cs, Fika.Core/Networking/FikaServer.cs, Fika.Core/UI/Patches/ChangeGameModeButton_Patch.cs, Fika.Core/UI/Patches/MenuTaskBar_Patch.cs, Fika.Core/Utils/ColorUtils.cs
Does exactly what it says on the tin. Correct pull request this time.
=> Replace all color tags with a more friendly function.

Fika.Core/Coop/Components/CoopHalloweenEventManager.cs, Fika.Core/Coop/GameMode/CoopGame.cs
=> Stage stuff I left unstaged in my previous PR

Fika.Core/Coop/ClientClasses/CoopClientSharedQuestController.cs
=> Fix quest sharing's dropping item happening recursively

Fika.Core/FikaPlugin.cs, Fika.Core/Networking/Websocket/EFikaNotifications.cs, Fika.Core/Networking/Websocket/FikaNotificationManager.cs, Fika.Core/Networking/Websocket/Notifications/PushNotification.cs, Fika.Core/Networking/Websocket/Notifications/ReceivedSentItemNotification.cs, Fika.Core/Networking/Websocket/Notifications/StartRaidNotification.cs, Fika.Core/UI/Patches/TarkovApplication_method_18_Patch.cs, Fika.Core/Utils/LocaleUtils.cs
See: https://github.com/project-fika/Fika-Server/pull/78
=> Feature: WS Notifications

Fika.Core/Coop/ClientClasses/HandsControllers/CoopClientFirearmController.cs
- Causes error for mods patching nested types
=> Fix parameter name not being same as parent

Fika.Core/Coop/Patches/LocalGame/TarkovApplication_LocalGameCreator_Patch.cs
- Should be handled on the server later
=> Fix raid presence getting reset after transit

Fika.Core/Coop/Custom/FikaDynamicAI.cs
- Should no longer spray bullets when being enabled from testing
- Now actually forces the paused state
=> Dynamic AI improvements

Fika.Core/Networking/Websocket/FikaNotificationManager.cs, Fika.Core/UI/Patches/TarkovApplication_method_18_Patch.cs
=> FikaNotificationManager changes

Fika.Core/Networking/Websocket/DedicatedRaidWebSocketClient.cs, Fika.Core/UI/Custom/MatchMakerUIScript.cs, Fika.Core/UI/Patches/MatchmakerAcceptScreen/MatchmakerAcceptScreen_Show_Patch.cs
Fixes a bug where the MMUI stays after getting kicked to main menu for inactivity (base game feature)
Bug report on Discord
=> Fix AFK bug

Fika.Core/UI/Custom/MatchMakerUIScript.cs
Don't destroy the gameobject when deleting MMUI
=> Don't destroy gameObject

Fika.Core/Coop/GameMode/CoopGame.cs
Fixes ForceSaveOnDeath, tested and working.
#204
=> Use new serializer & set ProfileId (Fixes: #204)

Fika.Core/UI/Custom/MatchMakerUIScript.cs
- Dispose of entire GameObject
This disposes of the entire `GameObject`, leaving no traces
=> Fix MMUI again

Fika.Core/Coop/Patches/Bugfixes/PartyInfoPanel_method_3_Patch.cs, Fika.Core/Utils/FikaModHandler.cs
Adds the bugfix from UI Fixes that fixes the bug if you inspect a player during loading, with permission from Tyfon
=> Add patch from UI Fixes

Fika.Core/Coop/Players/CoopPlayer.cs, Fika.Core/FikaPlugin.cs
Adds an option to receive ½ XP from all non-boss kills
=> Shared kill xp

Fika.Core/Coop/GameMode/CoopGame.cs, Fika.Core/Coop/Utils/BotExtensions.cs
=> Cleanup and separate bot logic

Fika.Core/Coop/GameMode/CoopGame.cs, Fika.Core/Coop/Players/CoopPlayer.cs
They should no longer improperly reset.
=> Fix transit quests

Fika.Core/Coop/Players/CoopPlayer.cs, Fika.Core/Coop/Players/ObservedCoopPlayer.cs
- Weapon was null, causing early return
- Fixes #207
=> Fix kills not tracking

Fika.Core/Coop/Players/CoopBot.cs, Fika.Core/Coop/Players/CoopPlayer.cs, Fika.Core/Coop/Players/ObservedCoopPlayer.cs
- Use correct Tag
- Fix if xp < 0
=> Fix shared XP

Fika.Core/Coop/GameMode/CoopGame.cs
- Should help figuring out where the dedi gets stuck
=> Add more logging

Fika.Core/Coop/ClientClasses/HandsControllers/CoopClientPortableRangeFinderController.cs, Fika.Core/Coop/Players/CoopPlayer.cs, Fika.Core/FikaPlugin.cs
- Also bump version
- Fixes https://github.com/project-fika/Fika-Plugin/issues/218
=> Fixes the range finder locally

Fika.Core/Coop/GameMode/CoopGame.cs, Fika.Core/FikaPlugin.cs, Fika.Core/Models/ClientConfigModel.cs, Fika.Core/Networking/Http/FikaRequestHandler.cs
- Closes https://github.com/project-fika/Fika-Plugin/issues/206
=> Adds support for server-side transit toggle

Fika.Core/Coop/ObservedClasses/HandsControllers/CoopObservedMedsController.cs
=> Implement operations

Fika.Core/UI/Custom/MainMenuUI.cs, Fika.Core/UI/Custom/MainMenuUIPlayer.cs, Fika.Core/UI/Custom/MainMenuUIScript.cs, Fika.Core/UI/FikaUIGlobals.cs, Fika.Core/Utils/LocaleUtils.cs
=> Localise main menu UI

Fika.Core/Coop/ObservedClasses/HandsControllers/CoopObservedMedsController.cs, Fika.Core/FikaPlugin.cs
=> Fix bot death nullref

Fika.Core/FikaPlugin.cs
- Cleanup every header to avoid errors
=> Cleanup every header to avoid errors

Fika.Core/Coop/Components/CorpsePositionSyncer.cs, Fika.Core/Coop/Players/CoopPlayer.cs, Fika.Core/Coop/Players/ObservedCoopPlayer.cs, Fika.Core/Networking/FikaClient.cs, Fika.Core/Networking/Packets/GameWorld/CorpsePositionPacket.cs
- Sync ragdolls from host to clients so that they end up relatively in the same position
=> Ragdoll Sync

Fika.Core/Coop/ObservedClasses/HandsControllers/CoopObservedFirearmController.cs
- Should resolve infinite firing bug
=> Change code for audio on player death

Fika.Core/Coop/Players/CoopPlayer.cs, Fika.Core/Coop/Players/ObservedCoopPlayer.cs, Fika.Core/Networking/FikaClient.cs, Fika.Core/Networking/FikaServer.cs, Fika.Core/Networking/Packets/Player/SideEffectPacket.cs
- Knife poison now works
- Charges sync
=> Fix cultist knife poison

Fika.Core/Coop/GameMode/CoopGame.cs, Fika.Core/Coop/Players/CoopPlayer.cs, Fika.Core/Coop/Players/ObservedCoopPlayer.cs, Fika.Core/FikaPlugin.cs, Fika.Core/Networking/FikaClient.cs, Fika.Core/Networking/FikaServer.cs, Fika.Core/Networking/Packets/Backend/InformationPacket.cs, Fika.Core/UI/Patches/MenuTaskBar_Patch.cs
- Fixes several errors due to locales having incorrect/unsupported data
=> Fix locale errors

Fika.Core/Coop/Components/CorpsePositionSyncer.cs, Fika.Core/Coop/GameMode/CoopGame.cs, Fika.Core/Coop/HostClasses/FikaHostWorld.cs, Fika.Core/Networking/FikaClient.cs, Fika.Core/Networking/FikaPingingClient.cs, Fika.Core/Networking/FikaSerializationExtensions.cs, Fika.Core/Networking/FikaServer.cs, Fika.Core/Networking/Packets/GameWorld/ThrowablePacket.cs, Fika.Core/Networking/Packets/GameWorld/WorldPacket.cs, Fika.Core/UI/Custom/MatchMakerUIScript.cs
Consolidates several packets into one packet, resulting in better allocations and less packet spam.
- Fixes #239
=> Consolidate packets

Fika.Core/Coop/GameMode/CoopGame.cs, Fika.Core/Coop/Patches/Overrides/FixSavageInventoryScreenPatch_Override.cs, Fika.Core/Coop/Players/CoopPlayer.cs, Fika.Core/Coop/Utils/FikaGlobals.cs, Fika.Core/Networking/FikaClient.cs, Fika.Core/Networking/FikaSerializationExtensions.cs, Fika.Core/Networking/FikaServer.cs, Fika.Core/Networking/Packets/GameWorld/ReconnectPacket.cs, Fika.Core/Networking/Packets/GameWorld/WorldLootPacket.cs
- Fixes and slightly reworks reconnect to work with .15 EFT
- Fixes #247
=> Fix reconnect

Fika.Core/Coop/Utils/FikaBackendUtils.cs, Fika.Core/Coop/Utils/FikaGlobals.cs, Fika.Core/Networking/FikaClient.cs, Fika.Core/Networking/FikaServer.cs, Fika.Core/UI/Patches/MatchmakerAcceptScreen/MatchmakerAcceptScreen_Show_Patch.cs
- Shows the scav profile on the loading screen while playing as a scav
=> Use Scav profile on loading screen

Fika.Core/Coop/GameMode/CoopGame.cs, Fika.Core/Networking/FikaClient.cs, Fika.Core/Networking/FikaServer.cs, Fika.Core/Networking/Packets/GameWorld/ExfiltrationPacket.cs
- Fixes scav exfils on reconnect
- Improves exfil sync overall
- Fixes #254
=> Rework exfil sync and fix scav reconnect

Fika.Core/Coop/Custom/FikaHealthBar.cs
- Should no longer pop up in the middle of the screen
- Now correctly applies alpha like the name plate itself
=> Fix effect rendering

Fika.Core/FikaPlugin.cs, Fika.Core/Utils/LocaleUtils.cs
- Added new error handling for locales
- Use fallback if an error is thrown
- Notify user about the caught error
=> Add error handling to locales and use fallbacks

Fika.Core/FikaPlugin.cs
- Should allow settings to remain after changing languages
=> New locale handling

Fika.Core/Coop/Patches/LocalGame/TarkovApplication_LocalGameCreator_Patch.cs
Release the `AbstractGame` singleton properly.
- Fixes #264
=> Fix singleton release

Fika.Core/Coop/GameMode/CoopGame.cs, Fika.Core/Modding/Events/FikaGameEndedEvent.cs, Fika.Core/Modding/Events/PeerConnectedEvent.cs, Fika.Core/Networking/FikaClient.cs, Fika.Core/Networking/FikaServer.cs
Add new events
- Game ended
- Peer connected
=> Add new events

Fika.Core/Coop/Components/CorpsePositionSyncer.cs, Fika.Core/Coop/Components/ItemPositionSyncer.cs, Fika.Core/Coop/Players/ObservedCoopPlayer.cs, Fika.Core/Coop/Utils/FikaGlobals.cs, Fika.Core/FikaPlugin.cs
- Removes the "pop" of items when a player dies
=> Fix inventory popping

Fika.Core/Coop/GameMode/CoopGame.cs
Fixes the black screen bug when using "Save on death"
=> Fix save on death bug

Fika.Core/UI/Patches/ItemContext_Patch.cs
- Don't allow sending items from mannequin view
=> Don't allow sending items from mannequin view

Fika.Core/Coop/GameMode/CoopGame.cs, Fika.Core/Coop/GameMode/IFikaGame.cs
- Fixes an issue where host gets the incorrect season
- Revamps the weather to be fetched earlier to prevent stutters at the very last stage
- Cleanup / refactor props
=> Season rework

Fika.Core/UI/Custom/MatchMakerUIScript.cs
1.Remove duplicate code.
2.Fixed headless client selection not working because of the [Commit#49eaf1cfd945959ce852a363104e23eb5f22316e](https://github.com/project-fika/Fika-Plugin/commit/49eaf1cfd945959ce852a363104e23eb5f22316e). (Maybe there will be a better way to solve this problem.)
=> Fixed headless client selection not working.

Fika.Core/Coop/Patches/LocalGame/TarkovApplication_LocalGameCreator_Patch.cs
Fixed scav raid time not match SPT's raidsetting
=> Fixed scav raid time not match SPT's raidsetting

Fika.Core/Console/FikaCommands.cs, Fika.Core/Coop/Components/BotStateManager.cs, Fika.Core/Coop/Components/CoopExfilManager.cs, Fika.Core/Coop/Components/CoopHandler.cs, Fika.Core/Coop/Components/CoopTimeManager.cs, Fika.Core/Coop/Custom/FikaDynamicAI.cs, Fika.Core/Coop/GameMode/BaseGameController.cs, Fika.Core/Coop/GameMode/ClientGameController.cs, Fika.Core/Coop/GameMode/CoopGame.cs, Fika.Core/Coop/GameMode/HostGameController.cs, Fika.Core/Coop/GameMode/IFikaGame.cs, Fika.Core/Coop/Patches/Artillery/ArtilleryServerProjectileClass_Constructor_Patch.cs, Fika.Core/Coop/Patches/Artillery/ServerShellingControllerClass_method_0_Patch.cs, Fika.Core/Coop/Patches/GrenadeClass_Init_Patch.cs, Fika.Core/Coop/Players/CoopBot.cs, Fika.Core/Coop/Players/CoopPlayer.cs, Fika.Core/Networking/FikaClient.cs, Fika.Core/Networking/FikaServer.cs, Fika.Core/Networking/Packets/GameWorld/GenericSubPackets.cs, Fika.Core/Networking/Packets/GameWorld/RequestSubPackets.cs
Takes apart a majority of `CoopGame` and adds the logic to a `BaseGameController`, allowing me to use more game modes for e.g. the Headless client.
=> 4.0/refactor

Fika.Core/FikaPlugin.cs
=> change UPnP and NAT punching to be Advanced options

Fika.Core/UI/Custom/MatchMakerUIScript.cs
I didn't test this because I'm not a nerd with a bunch of them.
=> Alphatecialize the headless clients for nerds with a bunch of them
