- LICENSE-SIT.md
- README.md
SIT is dual-licensed (implicit unlicense and explicit NCSA). The NCSA license provides the most clarity for right of use of the source code, thus the decision was made to update the license file.
Please let me know if there is any change required for the pull request.
> Improve clarity of SIT license

- Fika.Core/Coop/GameMode/CoopGame.cs
- Fika.Core/FikaPlugin.cs
Been tested by my group for more than 50+ raids. With MASSIVE fps improvements. (in some cases double fps) 
It also fixes one inherent issues with bot limits: before bosses could get blocked. They always get spawned now.
Spawning always cause some minor stutters. Technically not this code at fault. But it does allow for more opportunities to spawn things.  (Perhaps should be added to description of the setting in the plugin menu?) But personally, Ill take double fps for a tiny stutter every now and then.
> Despawn furthest bot on bot spawn

- Fika.Core/Coop/Custom/FikaHealthBar.cs
- Fika.Core/Coop/Factories/PingFactory.cs
- Fika.Core/Utils/WorldToScreen.cs
This PR implements optic zoom WorldToScreen resolution for both pings and coop player nameplates/health. Tested with Vudu 1x/6x, Valday 1x/6x, ADO 3x/9x, and Specter 1x/4x optics. Does not change default behavior for any reflex sight or optic with zoom level <= 1.0. Did not test with SSAA, but it shouldn't affect anything as both the worldCamera and opticCamera should scale the same and the screen scale logic was not changed.
> Fix for WorldToScreen with zoomed scopes

- Fika.Core/Coop/GameMode/CoopGame.cs
- Fika.Core/Coop/Players/CoopPlayer.cs
- Fika.Core/FikaPlugin.cs
- Fika.Core/Models/ClientConfigModel.cs
This adds some part of an initial anti alt-f4 implementation, I think it can get more fleshed out once reconnecting is added as there's no way to currently tell if a disconnection is on purpose or if the client just dropped out due to a bad internet or a game crash.
Eventually, maybe letting the host handle saving the profiles of clients might also be a good alternative.. But I'm not sure as to how feasible that is in the current system.
> Save profile immediately upon death

- Fika.Core/Coop/Players/CoopPlayer.cs
This change makes it so that items have to be examined in raid, the reason for this is that sometimes as a Scav you can find things like body armor or a backpack that are not yet examined. However then when you go out of raid you cannot take these into your inventory as you cannot examine them forcing you to sell to fence.
> Allow examination of items in raid

- Fika.Core/FikaPlugin.cs
- Fika.Core/Networking/Models/ModValidationResponse.cs
- Fika.Core/Utils/FikaModHandler.cs
In this PR I changed the BepInPlugin ID for FikaPlugin from "com.fika.core" to "com.project-fika.core". Any mods that required the ID to mark their plugin as required/incompatible will need to be updated to reflect this.
This notation is known as a "package" or "namespace". Typically the makeup is tld.domain.packagename. This is used to link back to the source. Typically developers who do not own a domain would use me.nexus4880.packagename though we own the domain project-fika.com, therefore we should be using that.
This wouldn't normally be something I'd even bring up though at the time of writing this fika.com is a registered domain and in my opinion we shouldn't attribute this package to them as they are not affiliated with this project.
> Added the mod verification logic

- Fika.Core/Coop/ClientClasses/CoopClientSharedQuestController.cs
- Fika.Core/FikaPlugin.cs
Since the type of quest is not given with counter.Type when the quest objective has multiple tasks (CounterCreator) make it possible for it to be checked.
This also modifies it so the initialization is a switch statement, as CounterCreator has a lot of conditions available and I feel that it's best to keep it in the current format (Kill, Item, Location etc) as well as turning 'Hit' into 'Item'
> Fix CounterCreator quest progression

- Fika.Core/Coop/Players/CoopPlayer.cs
Adds a check in CoopPlayer to check if the quest item is active and enabled, without this check anytime a user that still needs to do a quest it also gets replicated to users that have already done the quest causing them to get a useless quest item in their quest inventory (And in some cases causing the quest to be ready to be completed again)
> Check if quest item is Active and Enabled

- Fika.Core/Coop/BTR/FikaBTRManager_Client.cs
- Fika.Core/Coop/BTR/FikaBTRManager_Host.cs
This updates the BTR Manager components to the latest version of SPT, the BTR now no longer throws an exception on Woods which doesn't allow it to spawn.
We'll probably still have to look at syncing this thing better, but that's a thing for another time.
> Update BTR manager to latest

- Fika.Core/Coop/GameMode/CoopGame.cs
Since we now wait for plugins like SWAG + Donuts and Questing Bots, change the text status away from 'waiting for other players to finish loading'
> Update status at the end of vmethod_4

- Fika.Core/Coop/Airdrops/FikaAirdropsManager.cs
Throws error on clients otherwise, probably a good idea to keep this set anyway.
> Handle setting correct id on initialization of AirdropBox

- Fika.Core/Coop/Airdrops/FikaAirdropPlane.cs
Causes the headless host to crash if an airdrop is being dropped, handle this by checking if the manager is not null before trying to add the Projectile.
> Handle AirdropManager for adding projectiles being null on headless host

- Fika.Dedicated/FikaDedicatedPlugin.cs
- Fika.Dedicated/Patches/TextureValidateFormatPatch1.cs
- Fika.Dedicated/Patches/TextureValidateFormatPatch2.cs
- Fika.Dedicated/Patches/TextureValidateFormatPatch3.cs
This PR adds support for the unity parameter `-nographics`
Before marking this as ready i want to test some map (without and with the parameter) as a benchmark
performance was measured using this docker container https://github.com/zhliau/fika-headless-docker
and ``docker stats``
the values are rough average values measured during a normal raid
CPU usage was measured on a `AMD Ryzen 5 4500` (100% means 1 full core). a dedicated GPU was not installed
all of them were measured with 1 player and quite a bunch of mods installed (so dont see them as the most acurate values).
The container was also restarted after every raid.
The ram cleaner mod was also installed, but im not sure if that even works on linux.
| Map | CPU %  |  Memory GiB | CPU % (`-nographics`) | Memory (`-nographics`) |  
| …
> (HEADLESS CLIENT) add support for the `-nographics` paremeter

- Fika.Core/Coop/Custom/FikaDebug.cs
It covers up my health in the default position. Right now it doesn't save the position or anything, I just wanted to be able to move it out of the way easily.
> Make the debug window draggable

- Fika.Core/Coop/FreeCamera/FreeCamera.cs
I rewrote the freecam logic when cycling players to make it a bit easier to parse. Originally there was also a loop through all of the alive CoopPlayers each time we cycle the spectate-able players, even though we really only need to set the CurrentPlayer once. I removed that too.
> Freecam logic refactor

- Fika.Core/Coop/Players/CoopPlayer.cs
- Fika.Core/FikaPlugin.cs
- Removed damage multipliers (will become standalone mod at some point)
- Set Force Bind IP to 0.0.0.0 by default to prevent user error
> Cleanup configs

- Fika.Core/Coop/ObservedClasses/HandsControllers/CoopObservedMedsController.cs
- Should fix random swallowed nullrefs
> Add custom class for med operations

- Fika.Core/Coop/FreeCamera/FreeCameraController.cs
- Fika.Core/Coop/Patches/Class1374_ReloadBackendLocale_Patch.cs
- Fika.Core/Coop/Patches/Lighthouse/Zyriachy_Patches.cs
- Fika.Core/FikaPlugin.cs
- Fika.Core/UI/Custom/MatchMakerUIScript.cs
- Fika.Core/UI/Patches/FikaVersionLabel_Patch.cs
- Fika.Core/Utils/LocaleUtils.cs
- Adds bepinex localization
- Resolves https://github.com/project-fika/Fika-Plugin/issues/222
> Add new locales

- Fika.Core/Coop/Patches/Class1374_ReloadBackendLocale_Patch.cs
- Fika.Core/Coop/Players/CoopBot.cs
- Fika.Core/Coop/Players/CoopPlayer.cs
- Fika.Core/Coop/Players/ObservedCoopPlayer.cs
- Fika.Core/Networking/FikaClient.cs
> Fix and tweak kill sharing

- Fika.Core/Coop/Patches/GClass2013_method_0_Patch.cs
- Fika.Core/FikaPlugin.cs
Disables loading of server related scenes as a client
> Disable server scenes as client

- Fika.Core/UI/Custom/MainMenuUIScript.cs
- Show correct time on static time maps
> Show correct time on static time maps

- Fika.Core/Coop/GameMode/CoopGame.cs
- Fika.Core/Coop/Utils/FikaBackendUtils.cs
- Fika.Core/Networking/FikaClient.cs
- Fika.Core/Networking/FikaServer.cs
- Fika.Core/Networking/Packets/Backend/InformationPacket.cs
- Fika.Core/UI/Custom/MatchMakerUIScript.cs
- Fika.Core/UI/Patches/MenuTaskBar_Patch.cs
- Fika.Core/Utils/LocaleUtils.cs
- Game now starts when host clicks "Starts Raid", no more "Select amount of players"
> Game start rework

- Fika.Core/Coop/Patches/PlayerPatches/Player_SetDogtagInfo_Patch.cs
- Fika.Core/Coop/Patches/PlayerPatches/Player_method_144_Patch.cs
Transpiles immediate return patches that get called often.
> Transpile immediate return patches

- Fika.Core/FikaPlugin.cs
- Fika.Core/Models/HeadlessConfigModel.cs
- Fika.Core/Networking/FikaServer.cs
- Fika.Core/Networking/Http/FikaRequestHandler.cs
Fika Core changes for automatic headless restart. Added model and request handler to retrieve headless config from fika.jsonc.
Also fixed a null reference on WanIP when no public IP are provided (probably due to requesting the public IP too many times).
> Fika Core changes for automatic headless restart

- Fika.Core/Coop/GameMode/CoopGame.cs
Add missing parameters to fix wrong spawn point when using transit to travel between maps on headless client.
> Add missing parameters to fix wrong spawn point when using transit to travel between maps on headless client.

- Fika.Core/Networking/Http/FikaRequestHandler.cs
Fix the GetPublicIP method can't catch error and stuck on this logic.
For example, a connection error occurs when making the first API request, the error will appear in the console and subsequent logic will not continue to execute.This will cause can't check mod and let Fika plugin crc32 keep 0.
None
> Fix the GetPublicIP method can't catch error and stuck on this logic.
